"""
Base Strategy Interface.

All trading strategies must inherit from this base class.
This provides a consistent interface for backtesting and live execution.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Any


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    symbol: str
    side: str  # 'buy' or 'sell'
    quantity: Decimal
    order_type: str  # 'market', 'limit', 'bracket'
    limit_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    timestamp: datetime | None = None
    reason: str | None = None  # Explanation for educational purposes


@dataclass
class StrategyParams:
    """Parameters that can be configured for a strategy."""

    name: str
    description: str
    param_type: str  # 'int', 'float', 'bool', 'select'
    default: Any
    min_value: Any | None = None
    max_value: Any | None = None
    options: list[Any] | None = None  # For 'select' type


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Strategies must implement:
    - generate_signals(): The core trading logic
    - get_explanation(): Educational content about the strategy
    """

    name: str = "Base Strategy"
    description: str = "Abstract base strategy"

    @classmethod
    @abstractmethod
    def get_parameters(cls) -> list[StrategyParams]:
        """Return the configurable parameters for this strategy."""
        pass

    @classmethod
    @abstractmethod
    def get_explanation(cls) -> dict[str, str]:
        """
        Return educational content explaining the strategy.

        Returns:
            dict with keys:
            - 'overview': High-level explanation
            - 'how_it_works': Technical details
            - 'when_to_use': Market conditions where this works best
            - 'risks': What can go wrong
        """
        pass

    @abstractmethod
    async def generate_signals(
        self,
        symbols: list[str],
        params: dict[str, Any],
    ) -> list[Signal]:
        """
        Generate trading signals for the given symbols.

        Args:
            symbols: List of stock symbols to analyze
            params: Strategy parameters

        Returns:
            List of trading signals
        """
        pass
